services:
  auth:
    build:
      context: auth
      target: run
    depends_on:
      orchestrator:
        condition: service_started
      auth_db:
        condition: service_healthy
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"
    deploy:
      mode: replicated
      replicas: 5
    profiles: ["run"]
  
  test_auth:
    build:
      context: auth
      target: test
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"
    profiles: ["test"]
  
  auth_db:
    image: mariadb
    restart: always
    expose:
      - "3306"
    healthcheck:
        test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
        start_period: 1m
        start_interval: 10s
        interval: 1m
        timeout: 5s
        retries: 10
    environment:
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - ./auth/db/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - auth-data:/var/lib/mysql
    networks:
      - "net"
    profiles: ["run"]

networks:
  net:
    name: net

volumes:
  auth-data: