services:
  auth:
    build: auth
    depends_on:
      - orchestrator
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"
    deploy:
      mode: replicated
      replicas: 5

networks:
  net:
    name: net