services:
  auth:
    build:
      context: auth
      target: run
    depends_on:
      - orchestrator
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"
    deploy:
      mode: replicated
      replicas: 5
    profiles: ["run"]
  
  test_auth:
    build:
      context: auth
      target: test
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"
    profiles: ["test"]

networks:
  net:
    name: net