services:
  auth1:
    build:
      context: .
      dockerfile: auth/Dockerfile
    expose:
      - "3000"
    networks:
      - "net"
  auth2:
    build:
      context: .
      dockerfile: auth/Dockerfile
    expose:
      - "3000"
    networks:
      - "net"

networks:
  net:
    name: net