services:
  garage1:
    build:
      context: .
      dockerfile: garage/Dockerfile
    expose:
      - "3000"
    networks:
      - "net"
  garage2:
    build:
      context: .
      dockerfile: garage/Dockerfile
    expose:
      - "3000"
    networks:
      - "net"

networks:
  net:
    name: net