services:
  garage:
    build:
      context: garage
      target: run
    restart: always
    depends_on:
      orchestrator:
        condition: service_started
      garage_db:
        condition: service_healthy
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"
    deploy:
      mode: replicated
      replicas: ${N_REPLICAS_GARAGE}
    profiles: ["run"]
  
  test_garage:
    build:
      context: garage
      target: test
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"
    profiles: ["test"]

  garage_db:
    image: mariadb
    restart: always
    expose:
      - "3306"
    healthcheck:
        test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
        start_period: 1m
        start_interval: 10s
        interval: 1m
        timeout: 5s
        retries: 10
    environment:
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - ./garage/db/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - garage_db:/var/lib/mysql
    networks:
      - "net"
    attach: false
    profiles: ["run"]

networks:
  net:
    name: net


volumes:
  garage_db: