services:
  leaderboard:
    build:
      context: leaderboard
      target: run
    restart: always
    depends_on:
      - orchestrator
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"
    deploy:
      mode: replicated
      replicas: 5
    profiles: ["run"]
  
  test_leaderboard:
    build:
      context: leaderboard
      target: test
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"
    profiles: ["test"]

networks:
  net:
    name: net