services:
  leaderboard1:
    build:
      context: .
      dockerfile: leaderboard/Dockerfile
    expose:
      - "3000"
    networks:
      - "net"
  leaderboard2:
    build:
      context: .
      dockerfile: leaderboard/Dockerfile
    expose:
      - "3000"
    networks:
      - "net"

networks:
  net:
    name: net