services:
  orchestrator:
    build: orchestrator
    restart: always
    ports:
      - 5000:8080
    expose:
      - "${SERVICE_PORT}"
    environment:
      SESSION_KEY: secret
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"

networks:
  net:
    name: net