services:
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    ports:
      - 5000:8080
    expose:
      - "3000"
    networks:
      - "net"

networks:
  net:
    name: net