services:
  orchestrator:
    build: orchestrator
    restart: always
    ports:
      - 5000:8080
    expose:
      - "50051"
    environment:
      SESSION_KEY: secret
    networks:
      - "net"

networks:
  net:
    name: net