services:
  orchestrator:
    build: 
      context: orchestrator
      target: run
    restart: always
    ports:
      - 5000:8080
    expose:
      - "${SERVICE_PORT}"
    environment:
      SESSION_KEY: secret
      SERVICE_PORT: ${SERVICE_PORT}
      START_MONEY: ${START_MONEY}
      MONEY_WIN: ${MONEY_WIN}
      MONEY_LAST: ${MONEY_LAST}
      POINTS_WIN: ${POINTS_WIN}
      POINTS_LAST: ${POINTS_LAST}
    networks:
      - "net"
    profiles: ["run"]

  test_orchestrator:
    build: 
      context: orchestrator
      target: test
    expose:
      - "${SERVICE_PORT}"
    environment:
      SESSION_KEY: secret
      SERVICE_PORT: ${SERVICE_PORT}
      START_MONEY: ${START_MONEY}
      MONEY_WIN: ${MONEY_WIN}
      MONEY_LAST: ${MONEY_LAST}
      POINTS_WIN: ${POINTS_WIN}
      POINTS_LAST: ${POINTS_LAST}
    networks:
      - "net"
    profiles: ["test"]

networks:
  net:
    name: net