services:
  racing:
    build: racing
    depends_on:
      - orchestrator
    expose:
      - "${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
    networks:
      - "net"

networks:
  net:
    name: net