services:
  racing1:
    build:
      context: .
      dockerfile: racing/Dockerfile
    expose:
      - "3000"
    networks:
      - "net"
  racing2:
    build:
      context: .
      dockerfile: racing/Dockerfile
    expose:
      - "3000"
    networks:
      - "net"

networks:
  net:
    name: net